# Generated by Django 5.0.6 on 2026-04-29 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('variety', models.CharField(blank=True, max_length=100, null=True)),
                ('sowing_date', models.DateField()),
                ('area', models.FloatField()),
                ('soil_type', models.CharField(max_length=20)),
                ('irrigation_type', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('growth_stage', models.CharField(max_length=20)),
                ('health_status', models.CharField(max_length=20)),
                ('last_fertilizer', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
