# Generated by Django 5.0.6 on 2026-05-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MandiPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=150)),
                ('commodity', models.CharField(max_length=150)),
                ('variety', models.CharField(max_length=150)),
                ('grade', models.CharField(max_length=100)),
                ('arrival_date', models.DateField()),
                ('min_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('modal_price', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['state'], name='markets_man_state_30bc9f_idx'), models.Index(fields=['district'], name='markets_man_distric_bc6e04_idx'), models.Index(fields=['commodity'], name='markets_man_commodi_0bdd9c_idx'), models.Index(fields=['arrival_date'], name='markets_man_arrival_505cd0_idx'), models.Index(fields=['is_active'], name='markets_man_is_acti_7869a7_idx')],
                'unique_together': {('market', 'commodity', 'arrival_date')},
            },
        ),
    ]
